apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cgtask03
  name: cgtask03
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cgtask03
  template:
    metadata:
      labels:
        app: cgtask03
    spec:
      containers:
      - name: cgtask03
        image: 35.74.253.177:8083/docker-hosted/springapp:11
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP

      
#Service Type Loadbalancer
---
apiVersion: v1
kind: Service
metadata:
  labels: 
    app: cgtask03
    k8s-app: cgtask03
  name: cgtask03
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
  selector:
    app: cgtask03
